### ISSUE TITLE
Getting scan details for a specific project fails

### ISSUE THREAD

**Issue by jbrotsos** [checkmarx-ts/checkmarx-python-sdk#1]
When calling:

 def get_all_scans_for_project(self, project_id=None, scan_status=None, last=None):

With a specific project id and/or scan status, a crash is reported:

Traceback (most recent call last):
  File "get_stats.py", line 118, in <module>
    get_project_results()
  File "get_stats.py", line 42, in get_project_results
    scans = scan_api.get_all_scans_for_project(project.project_id)
  File "C:\Users\Cxadmin\AppData\Local\Programs\Python\Python38\lib\site-packages\CheckmarxPythonSDK\CxRestAPISDK\sast\scans\ScansAPI.py", line 164, in get_all_scans_for_project
    raise BadRequestError(r.text)
CheckmarxPythonSDK.CxRestAPISDK.exceptions.CxError.BadRequestError: BadRequestError(http_code=400, msg={
  "message": "The request is invalid.",
  "modelState": {
    "projectId": [
      "The value '210169projectId=210170' is not valid for Nullable`1."
    ]
  }
})

Example code:

def get_project_results():
    projects_api = ProjectsAPI()
    scan_api = ScansAPI()

    projects = projects_api.get_all_project_details()

    for project in projects:
        scans = scan_api.get_all_scans_for_project(project.project_id)

        for scan in scans:
            print (str(scan.id))

**Comment by cx-happy-yang** [comment]
This is a bug.

This issue happens, because I mistakenly used a class variable to store the URL related variable, for this issue, it is the "ScansAPI.all_scans_url" class variable.  So with consecutive call with this ScansAPI.get_all_scans_for_project method, the variable "projectId" is set with a wrong value. Instead of using a class variable, we should use a local variable to build the URL every time. I have refactored the source code to change all related URL variables to local variables. 

Please upgrade your CheckmarxPythonSDK, by " pip install --upgrade CheckmarxPythonSDK". This will make you upgrade CheckmarxPythonSDK to version 0.0.2.  Please test again.

Thanks.
