### ISSUE TITLE
CxRestAPI : link between Sast Reports and scans

### ISSUE THREAD

**Issue by GATINEAU85** [checkmarx-ts/checkmarx-python-sdk#101]
Hi, 
I use CheckmarxPythonSDK and the CxRestAPISDK to collect vulnerabilities on projects. However, I don't understand how I can collect SAST reports informations thanks to the last SAST scan. Is it possible to get the last report id for a specific scan ? 

My process is : 
```python
projects = ProjectsAPI.get_all_project_details()
for project in projects:
    scan = ScansAPI.get_last_scan_id_of_a_project(project_id=project.project_id)
    # Then, to get report id of this scan, we must generate a new report
    report = ScansAPI.register_scan_report(scan_id=scan.id)
    report_id = report.id
```

In this case, we must register a new report to get it after. I read the swagger and the documentation but I don't understand how I can get the last report id of the last scan of a project. 

Thanks

**Comment by cx-happy-yang** [comment]
Hi @GATINEAU85 ,

You can follow this example: https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/858cc457b4445061b5f24cc94b52069ccba565b7/examples/scan_from_local_zip.py#L120

By the way, you can find the definition of the method register_scan_report: https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/858cc457b4445061b5f24cc94b52069ccba565b7/CheckmarxPythonSDK/CxRestAPISDK/ScansAPI.py#L827

It returned a CxRegisterScanReportResponse object. The field report_id is what you expecting to have.

Best regards.
Happy

**Comment by GATINEAU85** [comment]
Hi,

Thank you for your reply. I may have misspoken in my question.

I've actually read this method before and I get the report id correctly.

However, I would like to know if it is possible to retrieve the id of the last report from a scan. It is not logical to recover the identifier of the last report of a scan by having to generate a new one.

So my question is, how to retrieve the identifier of a report from a scan without having to generate a new one each time ?
Thanks
Best regards
GATINEAU85

**Comment by cx-happy-yang** [comment]
Hi @GATINEAU85 ,

Unfortunately there is no such API. 

The report generation is done by CxSAST Jobs Manager, and the file created under C:\CxReports folder. 

I think the reason why CxSAST does not offer such API,  is that people may generate any number of different report files for the same scan, because of the combinations of the report filter settings.  It is not very meaningful to store all such information (the report id, the filter settings) in database, and report files could be deleted anytime by data retention. People could just generate a new report anytime they need. That will make the reports management way easier.

The report could be generated by Rest API, or through Web Portal.

By the way, the REST API that used to register new report does not offer the functionality of filtering, we have Portal SOAP API for it, which is also used by Web Portal. If you want to use that one, you can follow this example:
https://github.com/checkmarx-ts/checkmarx-python-sdk/blob/012c81bc821431fdcb1d6823924accf7b56e48c9/examples/generate_report_without_not_exploitable_results.py#L74

Best regards.
Happy
